name: Build tig-native algorithm

on:
  workflow_dispatch:
    inputs:
      challenge_type:
        description: 'Challenge type to build'
        required: true
        type: choice
        options:
          - knapsack
          - satisfiability
          - vector-search
          - vehicle-routing
      algorithm_name:
        description: 'Algorithm name'
        required: true
        type: string
      llvm_release:
        description: 'LLVM release index (defaults to latest)'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-22.04-arm
    container:
      image: debian:12
    permissions:
      contents: write
      statuses: write
    steps:
      - name: Install git
        run: |
          apt-get update -y
          apt-get install git -y
          
      - uses: actions/checkout@v4

      - name: Build tig-native
        env:
          LLVM_RELEASE: ${{ inputs.llvm_release }}
        run: |
          chmod +x tig-native/build.sh
          cd tig-native
          ./build.sh --${{ inputs.challenge_type }} .
          cd ..

      - name: Copy to algorithms directory
        run: |
          CHALLENGE_DIR=$(echo "${{ inputs.challenge_type }}" | tr '-' '_')
          mkdir -p tig-algorithms/native/${CHALLENGE_DIR}
          cp tig-native/rtsig_blob.dylib tig-algorithms/native/${CHALLENGE_DIR}/${{ inputs.algorithm_name }}.native

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rtsig-blob-${{ inputs.challenge_type }}-${{ github.sha }}
          path: tig-native/rtsig_blob.dylib

      - name: Auto commit
        id: auto_commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Compiled native algorithm ${{ inputs.algorithm_name }} for ${{ inputs.challenge_type }}
  
      - name: Update Commit Status (Success)
        if: success()
        uses: myrotvorets/set-commit-status-action@master
        with:
          status: 'success'
          sha: ${{ steps.auto_commit.outputs.commit_hash }}

      - name: Update Commit Status (Failure)
        if: failure()
        uses: myrotvorets/set-commit-status-action@master
        with:
          status: 'failure'